services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=storeinhome
      - POSTGRES_USER=francisco
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234567
    ports:
      - "5050:80"
